Flat/framework
Limit-Theory-Redux/ltheory pull request #28
Opened 2023-03-01 17:04 UTC by Flatfingers

This set of changes enables basic economic AI and performs some cleanup on various associated elements (including System Map and HUD).

2023-03-01 18:09 UTC, IllustrisJack requested changes

2023-03-01 18:09 UTC, IllustrisJack commented on script/States/App/LTheoryRedux.lua
> +      if not playerShip:isDestroyed() and not playerShip:isShipDocked() and target ~= nil and target ~= playerShip then
intendation

2023-03-02 10:50 UTC, IllustrisJack approved these changes
Not gonna be in your way, but I highly recommend to define coding conventions :)

2023-03-02 21:37 UTC, merged

2023-03-02 21:40 UTC, Flatfingers commented
> Not gonna be in your way, but I highly recommend to define coding conventions :)

Thank you for the review/approval! I have been putting together some general guidelines -- basically "follow Josh's style." I'll publish them once I have a little more detail.